In [9]:
import nltk
import numpy as np

In [10]:
paragraph = """ Tom love Stephanie. Jerry love Bob. Bob, Stephanie and Tom love Jerry. Tom don't look good during eating. """

In [11]:
# Cleaning the texts
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer

In [12]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)

print(sentences)

corpus = []

[' Tom love Stephanie.', 'Jerry love Bob.', 'Bob, Stephanie and Tom love Jerry.', "Tom don't look good during eating."]


In [13]:
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    #review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = [wordnet.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)
    print(corpus)
    print("_______________________________________________________________________________________")

['tom love stephanie']
_______________________________________________________________________________________
['tom love stephanie', 'jerry love bob']
_______________________________________________________________________________________
['tom love stephanie', 'jerry love bob', 'bob stephanie tom love jerry']
_______________________________________________________________________________________
['tom love stephanie', 'jerry love bob', 'bob stephanie tom love jerry', 'tom look good eating']
_______________________________________________________________________________________


In [14]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

In [15]:
print(X)

[[0 0 0 0 0 1 1 1]
 [1 0 0 1 0 1 0 0]
 [1 0 0 1 0 1 1 1]
 [0 1 1 0 1 0 0 1]]
