In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [54]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [55]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [42]:
voc_size=10000

In [43]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[8828, 6655, 3601, 7903], [8828, 6655, 3601, 6136], [8828, 5262, 3601, 6820], [1063, 7983, 8636, 7706, 4090], [1063, 7983, 8636, 7706, 8575], [3861, 8828, 5826, 3601, 1679], [6352, 8341, 4538, 7706]]


In [44]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [45]:
import numpy as np

In [46]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8828 6655 3601 7903]
 [   0    0    0    0 8828 6655 3601 6136]
 [   0    0    0    0 8828 5262 3601 6820]
 [   0    0    0 1063 7983 8636 7706 4090]
 [   0    0    0 1063 7983 8636 7706 8575]
 [   0    0    0 3861 8828 5826 3601 1679]
 [   0    0    0    0 6352 8341 4538 7706]]


In [47]:
dim=10

In [48]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [49]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [50]:
print(model.predict(embedded_docs))

[[[-8.68704170e-03  1.05343461e-02  4.89387549e-02  7.33394548e-03
    2.36598887e-02  3.69598158e-02 -2.35366356e-02 -2.94533372e-02
   -3.45462449e-02 -3.87181863e-02]
  [-8.68704170e-03  1.05343461e-02  4.89387549e-02  7.33394548e-03
    2.36598887e-02  3.69598158e-02 -2.35366356e-02 -2.94533372e-02
   -3.45462449e-02 -3.87181863e-02]
  [-8.68704170e-03  1.05343461e-02  4.89387549e-02  7.33394548e-03
    2.36598887e-02  3.69598158e-02 -2.35366356e-02 -2.94533372e-02
   -3.45462449e-02 -3.87181863e-02]
  [-8.68704170e-03  1.05343461e-02  4.89387549e-02  7.33394548e-03
    2.36598887e-02  3.69598158e-02 -2.35366356e-02 -2.94533372e-02
   -3.45462449e-02 -3.87181863e-02]
  [ 8.06634501e-03  1.12443194e-02 -2.70895846e-02 -8.54908302e-03
    3.27388905e-02 -4.82186452e-02 -1.79743543e-02  1.89144872e-02
    3.34852971e-02  3.43304165e-02]
  [-1.72904506e-02 -3.94765623e-02  4.65674885e-02  3.94468941e-02
    2.18617581e-02 -3.12575698e-02 -4.00529057e-03  3.75204422e-02
    4.15426530e-

In [51]:
embedded_docs[0]

array([   0,    0,    0,    0, 8828, 6655, 3601, 7903])

In [52]:
print(model.predict(embedded_docs)[0])

[[-8.6870417e-03  1.0534346e-02  4.8938755e-02  7.3339455e-03
   2.3659889e-02  3.6959816e-02 -2.3536636e-02 -2.9453337e-02
  -3.4546245e-02 -3.8718186e-02]
 [-8.6870417e-03  1.0534346e-02  4.8938755e-02  7.3339455e-03
   2.3659889e-02  3.6959816e-02 -2.3536636e-02 -2.9453337e-02
  -3.4546245e-02 -3.8718186e-02]
 [-8.6870417e-03  1.0534346e-02  4.8938755e-02  7.3339455e-03
   2.3659889e-02  3.6959816e-02 -2.3536636e-02 -2.9453337e-02
  -3.4546245e-02 -3.8718186e-02]
 [-8.6870417e-03  1.0534346e-02  4.8938755e-02  7.3339455e-03
   2.3659889e-02  3.6959816e-02 -2.3536636e-02 -2.9453337e-02
  -3.4546245e-02 -3.8718186e-02]
 [ 8.0663450e-03  1.1244319e-02 -2.7089585e-02 -8.5490830e-03
   3.2738890e-02 -4.8218645e-02 -1.7974354e-02  1.8914487e-02
   3.3485297e-02  3.4330416e-02]
 [-1.7290451e-02 -3.9476562e-02  4.6567488e-02  3.9446894e-02
   2.1861758e-02 -3.1257570e-02 -4.0052906e-03  3.7520442e-02
   4.1542653e-02 -3.3963472e-05]
 [ 3.0102741e-02 -1.0822665e-02 -3.1215787e-02  2.6349451e